<script setup lang="ts">
import { TrendingUp, LayoutDashboard, GitCompare, Leaf, Zap, Droplet, AlertTriangle, Sun, Moon, Download, Hexagon, BarChart3 } from 'lucide-vue-next'

// State: Use Cookie for persistence. Default to true (Dark Mode)
const activeTab = ref('single')
const chartType = ref<'bar' | 'radar'>('bar') // New Chart Type State
const isDark = useCookie<boolean>('theme', { default: () => true }) 

const toggleTheme = () => isDark.value = !isDark.value

// Scenario A Inputs
const inputsA = ref({ crops: 50, renewables: 30, waterEff: 40 })
// Scenario B Inputs
const inputsB = ref({ crops: 75, renewables: 60, waterEff: 20 })

// Fetch Data (Reactive)
// We now pass a unique ID ('scenario-a', 'scenario-b') to ensure they don't overwrite each other
const { fetchProjections } = useNexusModel()
const { data: outputsA } = await fetchProjections('scenario-a', inputsA)
const { data: outputsB } = await fetchProjections('scenario-b', inputsB)

// --- PRESETS LOGIC ---
const applyPreset = (targetInput: any, type: string) => {
  if (type === 'sustainable') {
    targetInput.value = { crops: 60, renewables: 80, waterEff: 90 }
  } else if (type === 'industrial') {
    targetInput.value = { crops: 90, renewables: 20, waterEff: 30 }
  } else if (type === 'balanced') {
    targetInput.value = { crops: 50, renewables: 50, waterEff: 50 }
  }
}

// --- EXPORT REPORT LOGIC ---
const downloadReport = () => {
  const reportData = {
    timestamp: new Date().toLocaleString(),
    scenarioA: {
      description: "Primary Scenario",
      inputs: inputsA.value,
      outputs: outputsA.value
    },
    scenarioB: activeTab.value === 'compare' ? {
      description: "Comparison Scenario",
      inputs: inputsB.value,
      outputs: outputsB.value
    } : null,
    notes: "Generated by NexusModeler Interactive Platform"
  }

  // Create text content
  const textContent = JSON.stringify(reportData, null, 2)
  
  // Trigger download
  const blob = new Blob([textContent], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `nexus-report-${Date.now()}.json`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// --- Dynamic Analysis Logic ---

const analysisMessages = computed(() => {
  const msgs = []
  const inp = inputsA.value
  const out = outputsA.value

  // 1. Water Stress Logic (High = Bad)
  if (out.water > 75) {
    msgs.push({
      type: 'danger',
      icon: AlertTriangle,
      text: "CRITICAL: Water stress is dangerously high."
    })
    if (inp.waterEff < 40) {
      msgs.push({
        type: 'warning',
        icon: Droplet,
        text: "Low water efficiency is a major contributor. Consider raising efficiency above 50%."
      })
    }
  } else if (out.water > 50) {
    msgs.push({
      type: 'info',
      icon: Droplet,
      text: "Water stress is moderate. Monitor closely if crop intensity increases."
    })
  }

  // 2. Food Security Logic (Low = Bad)
  if (out.food < 45) {
    msgs.push({
      type: 'warning',
      icon: Leaf,
      text: "Food security is insufficient. Increase crop intensity to meet demand."
    })
  } else if (out.food > 80) {
    msgs.push({
      type: 'success',
      icon: Leaf,
      text: "Food security targets are comfortably met."
    })
  }

  // 3. Energy Logic
  if (inp.renewables > 70 && out.energy < 60) {
    msgs.push({
      type: 'info',
      icon: Zap,
      text: "High renewables usually improve security, but grid stability might be affecting the score."
    })
  }

  return msgs
})

const comparisonSummary = computed(() => {
  const foodDiff = outputsB.value.food - outputsA.value.food
  const energyDiff = outputsB.value.energy - outputsA.value.energy
  const waterDiff = outputsB.value.water - outputsA.value.water // Positive = More Stress (Bad)

  let summary = `Scenario B results in a `
  
  if (foodDiff > 5) summary += `significant boost to food security (+${foodDiff.toFixed(0)}) `
  else if (foodDiff < -5) summary += `drop in food security (${foodDiff.toFixed(0)}) `
  else summary += `similar food security profile `

  summary += `while `

  if (waterDiff > 5) summary += `increasing water stress levels (+${waterDiff.toFixed(0)}). `
  else if (waterDiff < -5) summary += `alleviating water stress (${waterDiff.toFixed(0)}). `
  else summary += `maintaining stable water levels. `

  return summary
})

</script>

<template>
  <div :class="{ dark: isDark }" class="h-screen flex flex-col overflow-hidden bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100">
    
    <!-- App Header -->
    <header class="h-16 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between px-4 md:px-6 shrink-0 z-20">
      <!-- ... Header content ... -->
      <div class="flex items-center gap-2 md:gap-4">
        <NuxtLink to="/" class="flex items-center gap-2 group">
           <div class="bg-indigo-600 text-white p-1.5 rounded shadow-sm">
              <TrendingUp :size="18" />
            </div>
            <span class="font-bold hidden md:inline">NexusModeler</span>
        </NuxtLink>
        <div class="hidden md:block h-6 w-px bg-slate-200 dark:bg-slate-700 mx-2"></div>
        <!-- Tab Switcher -->
        <nav class="flex bg-slate-100 dark:bg-slate-800 p-1 rounded-lg">
           <button @click="activeTab = 'single'" :class="['px-2 md:px-3 py-1.5 text-xs font-semibold rounded-md flex gap-2 transition-all', activeTab === 'single' ? 'bg-white dark:bg-slate-700 shadow-sm text-indigo-700 dark:text-indigo-300' : 'text-slate-500']">
             <LayoutDashboard :size="14" /> <span class="hidden sm:inline">Single</span>
           </button>
           <button @click="activeTab = 'compare'" :class="['px-2 md:px-3 py-1.5 text-xs font-semibold rounded-md flex gap-2 transition-all', activeTab === 'compare' ? 'bg-white dark:bg-slate-700 shadow-sm text-indigo-700 dark:text-indigo-300' : 'text-slate-500']">
             <GitCompare :size="14" /> <span class="hidden sm:inline">Compare</span>
           </button>
        </nav>
      </div>

      <!-- Add Toggle Button -->
      <div class="flex items-center gap-2 md:gap-3">
          <button @click="downloadReport" title="Export Report" class="p-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors text-slate-500 dark:text-slate-400">
            <Download :size="20" />
          </button>
          <button @click="toggleTheme" class="p-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
            <Sun v-if="isDark" :size="20" class="text-slate-500 dark:text-slate-400" />
            <Moon v-else :size="20" class="text-slate-500 dark:text-slate-400" />
          </button>
          <!-- ... existing buttons ... -->
      </div>
    </header>

    <!-- RESPONSIVE LAYOUT CHANGE: flex-col on mobile, flex-row on desktop -->
    <div class="flex flex-1 flex-col md:flex-row overflow-hidden">
      <!-- Sidebar Controls -->
      <aside class="w-full md:w-80 bg-white dark:bg-slate-900 border-b md:border-b-0 md:border-r border-slate-200 dark:border-slate-800 p-4 md:p-6 overflow-y-auto shrink-0">
        <h2 class="text-sm font-bold uppercase tracking-wider mb-6 flex items-center gap-2 text-slate-900 dark:text-white">
          <span class="w-1.5 h-4 bg-indigo-500 rounded-full"></span> Policy Levers
        </h2>
        
        <!-- Inputs A -->
        <div class="space-y-4">
           <div class="bg-indigo-50 dark:bg-slate-800 p-2 rounded-lg text-center text-xs font-bold text-indigo-700 dark:text-indigo-400 flex justify-between items-center">
             <span>SCENARIO A</span>
             <!-- Presets for A -->
             <div class="flex gap-1">
               <button @click="applyPreset(inputsA, 'sustainable')" title="Sustainable" class="w-4 h-4 rounded-full bg-emerald-400 hover:scale-125 transition-transform"></button>
               <button @click="applyPreset(inputsA, 'industrial')" title="Industrial" class="w-4 h-4 rounded-full bg-amber-400 hover:scale-125 transition-transform"></button>
               <button @click="applyPreset(inputsA, 'balanced')" title="Balanced" class="w-4 h-4 rounded-full bg-blue-400 hover:scale-125 transition-transform"></button>
             </div>
           </div>
           
           <div class="space-y-2">
             <SliderControl label="Crop Intensity" :icon="Leaf" v-model="inputsA.crops" colorClass="text-emerald-500" />
             <SliderControl label="Renewables %" :icon="Zap" v-model="inputsA.renewables" colorClass="text-amber-500" />
             <SliderControl label="Water Eff." :icon="Droplet" v-model="inputsA.waterEff" colorClass="text-cyan-500" />
           </div>
        </div>

        <!-- Inputs B (Conditional) -->
        <div v-if="activeTab === 'compare'" class="mt-8 pt-8 border-t border-slate-100 dark:border-slate-800 space-y-4 animate-fade-up">
           <div class="bg-purple-50 dark:bg-slate-800 p-2 rounded-lg text-center text-xs font-bold text-purple-700 dark:text-purple-400 flex justify-between items-center">
             <span>SCENARIO B</span>
             <!-- Presets for B -->
             <div class="flex gap-1">
               <button @click="applyPreset(inputsB, 'sustainable')" title="Sustainable" class="w-4 h-4 rounded-full bg-emerald-400 hover:scale-125 transition-transform"></button>
               <button @click="applyPreset(inputsB, 'industrial')" title="Industrial" class="w-4 h-4 rounded-full bg-amber-400 hover:scale-125 transition-transform"></button>
               <button @click="applyPreset(inputsB, 'balanced')" title="Balanced" class="w-4 h-4 rounded-full bg-blue-400 hover:scale-125 transition-transform"></button>
             </div>
           </div>

           <div class="space-y-2">
             <SliderControl label="Crop Intensity" :icon="Leaf" v-model="inputsB.crops" colorClass="text-emerald-500" />
             <SliderControl label="Renewables %" :icon="Zap" v-model="inputsB.renewables" colorClass="text-amber-500" />
             <SliderControl label="Water Eff." :icon="Droplet" v-model="inputsB.waterEff" colorClass="text-cyan-500" />
           </div>
        </div>
      </aside>

      <!-- Main Viz Area -->
      <main class="flex-1 p-4 md:p-8 overflow-y-auto bg-slate-50 dark:bg-slate-950">
        <!-- Visuals Header with Chart Type Toggle -->
        <div class="flex justify-between items-end mb-6">
          <h2 class="text-xl font-bold text-slate-800 dark:text-white hidden md:block">Visual Impact Projections</h2>
          
          <div class="flex bg-white dark:bg-slate-800 p-1 rounded-lg border border-slate-200 dark:border-slate-700 ml-auto">
            <button @click="chartType = 'bar'" :class="['p-1.5 rounded transition-colors', chartType === 'bar' ? 'bg-indigo-100 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-300' : 'text-slate-400 hover:text-slate-600']">
              <BarChart3 :size="18" />
            </button>
            <button @click="chartType = 'radar'" :class="['p-1.5 rounded transition-colors', chartType === 'radar' ? 'bg-indigo-100 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-300' : 'text-slate-400 hover:text-slate-600']">
              <Hexagon :size="18" />
            </button>
          </div>
        </div>

        <!-- RESPONSIVE GRID: Force 1 column on mobile, 2 columns on lg screens only when comparing -->
        <div :class="['grid gap-6', activeTab === 'compare' ? 'grid-cols-1 lg:grid-cols-2' : 'grid-cols-1']">
          
          <!-- Card A -->
          <Card class="p-4 md:p-6 animate-fade-up">
            <div class="flex justify-between items-center mb-6">
                <h3 class="font-semibold text-slate-800 dark:text-slate-100">Scenario A Outcomes</h3>
                <Badge color="blue">Primary</Badge>
            </div>
            
            <div class="bg-slate-50 dark:bg-slate-900/50 rounded-xl p-2 md:p-4 border border-slate-100 dark:border-slate-700 mb-6">
               <NexusChart v-if="outputsA" :data="outputsA" :type="chartType" />
            </div>
            
            <!-- Stat Cards A -->
            <div class="grid grid-cols-3 gap-2 md:gap-4">
                <StatCard label="Food Index" :value="outputsA.food" color="emerald" />
                <StatCard label="Energy Index" :value="outputsA.energy" color="amber" />
                <StatCard label="Water Index" :value="outputsA.water" color="cyan" />
            </div>

            <!-- Trade-off Analysis -->
            <div class="mt-6 pt-6 border-t border-slate-100 dark:border-slate-700">
                <h4 class="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3 flex items-center gap-2">
                  <AlertTriangle :size="14" class="text-slate-400"/> Trade-off Analysis
                </h4>
                <div class="space-y-2 text-sm text-slate-600 dark:text-slate-400">
                  <div v-if="outputsA.water < 40" class="flex gap-2 items-start text-amber-700 dark:text-amber-300 bg-amber-50 dark:bg-amber-900/20 p-2 rounded">
                      <AlertTriangle :size="14" class="mt-0.5 shrink-0" /> 
                      Warning: Water stress is critically high due to low efficiency.
                  </div>
                  <div v-if="outputsA.food > 80" class="flex gap-2 items-start text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-900/20 p-2 rounded">
                      <Leaf :size="14" class="mt-0.5 shrink-0" /> 
                      Food security goals met.
                  </div>
                  <p class="text-slate-500 dark:text-slate-500">Increasing crop intensity by 10% will degrade water levels by roughly 5% unless efficiency is improved.</p>
                </div>
            </div>
          </Card>

          <!-- Card B -->
          <Card v-if="activeTab === 'compare'" class="p-4 md:p-6 border-indigo-200 dark:border-indigo-800 relative overflow-hidden animate-fade-up animate-delay-100">
             <div class="absolute top-0 right-0 w-24 h-24 bg-purple-100 dark:bg-purple-900/20 rounded-bl-full -mr-10 -mt-10 opacity-50 pointer-events-none"></div>
             
             <div class="flex justify-between items-center mb-6">
                <h3 class="font-semibold text-slate-800 dark:text-slate-100">Scenario B Outcomes</h3>
                <Badge color="amber">Experimental</Badge>
             </div>

             <div class="bg-slate-50 dark:bg-slate-900/50 rounded-xl p-2 md:p-4 border border-slate-100 dark:border-slate-700 mb-6">
               <NexusChart v-if="outputsB" :data="outputsB" :type="chartType" />
            </div>
             
             <!-- Stat Cards B (Comparison Logic) -->
             <div class="grid grid-cols-3 gap-2 md:gap-4">
                <!-- Food Comparison -->
                <div class="bg-white dark:bg-slate-800 p-2 md:p-3 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm">
                    <div class="flex justify-between items-end">
                        <div class="text-[10px] md:text-xs text-slate-500 dark:text-slate-400 font-semibold mb-1">Food</div>
                        <div :class="['text-[10px] md:text-xs font-bold', outputsB.food > outputsA.food ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-600 dark:text-red-400']">
                           {{ outputsB.food > outputsA.food ? '+' : '' }}{{ (outputsB.food - outputsA.food).toFixed(0) }}
                        </div>
                    </div>
                    <div class="text-lg md:text-xl font-bold text-slate-800 dark:text-slate-100">{{ outputsB.food.toFixed(0) }}</div>
                </div>
                <!-- Energy Comparison -->
                <div class="bg-white dark:bg-slate-800 p-2 md:p-3 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm">
                    <div class="flex justify-between items-end">
                        <div class="text-[10px] md:text-xs text-slate-500 dark:text-slate-400 font-semibold mb-1">Energy</div>
                        <div :class="['text-[10px] md:text-xs font-bold', outputsB.energy > outputsA.energy ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-600 dark:text-red-400']">
                           {{ outputsB.energy > outputsA.energy ? '+' : '' }}{{ (outputsB.energy - outputsA.energy).toFixed(0) }}
                        </div>
                    </div>
                    <div class="text-lg md:text-xl font-bold text-slate-800 dark:text-slate-100">{{ outputsB.energy.toFixed(0) }}</div>
                </div>
                <!-- Water Comparison -->
                <div class="bg-white dark:bg-slate-800 p-2 md:p-3 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm">
                    <div class="flex justify-between items-end">
                        <div class="text-[10px] md:text-xs text-slate-500 dark:text-slate-400 font-semibold mb-1">Water</div>
                        <div :class="['text-[10px] md:text-xs font-bold', outputsB.water > outputsA.water ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-600 dark:text-red-400']">
                           {{ outputsB.water > outputsA.water ? '+' : '' }}{{ (outputsB.water - outputsA.water).toFixed(0) }}
                        </div>
                    </div>
                    <div class="text-lg md:text-xl font-bold text-slate-800 dark:text-slate-100">{{ outputsB.water.toFixed(0) }}</div>
                </div>
             </div>

             <div class="mt-6 pt-6 border-t border-slate-100 dark:border-slate-700 bg-indigo-50/50 dark:bg-indigo-900/10 -mx-6 -mb-6 p-6">
                <h4 class="text-sm font-semibold text-indigo-900 dark:text-indigo-300 mb-2">"What Changed?"</h4>
                <p class="text-sm text-indigo-700 dark:text-indigo-300 leading-relaxed">
                  {{ comparisonSummary }}
                </p>
             </div>
          </Card>

        </div>
      </main>
    </div>
  </div>
</template>
